name: "Setup"
inputs:
  working-directory:
    required: true
runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
    - uses: bahmutov/npm-install@v1
      with:
        working-directory: ${{ inputs.working-directory }}
