name: "App Name"
description: Generates the Fly.io app name for a preview deployment based on the current Git commit
inputs:
  component:
    required: true
    description: The component for which the app name should be generated (frontend or cms)
outputs:
  app-name:
    value: ${{ steps.app-name.outputs.app-name }}
    description: The name of the Fly.io app
  app-domain:
    value: ${{ steps.app-name.outputs.app-domain }}
    description: The domain of the Fly.io app
  app-url:
    value: ${{ steps.app-name.outputs.app-url }}
    description: The URL of the Fly.io app
runs:
  using: "composite"
  steps:
    - id: app-name
      run: |
        GITHUB_SHA_SHORT=${GITHUB_SHA::4}
        GITHUB_HEAD_REF_SHORT=${GITHUB_HEAD_REF::25}

        case ${{ inputs.component }} in
          frontend)
            APP_NAME=lapuertahostels-preview-$GITHUB_HEAD_REF_SHORT-$GITHUB_SHA_SHORT
            echo "app-name=$APP_NAME" >> $GITHUB_OUTPUT
            ;;
          cms)
            APP_NAME=lapuertahostels-cms-preview-$GITHUB_HEAD_REF_SHORT-$GITHUB_SHA_SHORT
            echo "app-name=$APP_NAME" >> $GITHUB_OUTPUT
            ;;
        esac

        APP_DOMAIN=$APP_NAME.fly.dev
        echo "app-domain=$APP_DOMAIN" >> $GITHUB_OUTPUT

        APP_URL=https://$APP_DOMAIN
        echo "app-url=$APP_URL" >> $GITHUB_OUTPUT
      shell: bash
