name: "Populate CMS Types"
description: "Generates the CMS types and copies them to the frontend"
runs:
  using: "composite"
  steps:
    - name: "Install dependencies"
      run: pnpm --filter cms install
      shell: bash
      working-directory: cms
    - run: pnpm generate:types
      shell: bash
      working-directory: cms
    - run: pnpm copy-types
      shell: bash
      working-directory: frontend
