name: "Populate CMS Types"
shell
runs:
  using: "composite"
  steps:
    - uses: bahmutov/npm-install@v1
      with:
        working-directory: cms
    - run: npm run generate:types
      shell: bash
      working-directory: cms
    - run: npm run copy-types
      shell: bash
      working-directory: frontend
