name: "Populate CMS Types"
runs:
  using: "composite"
  steps:
    - name: "Install dependencies"
      run: pnpm install --filter cms
      shell: bash
      working-directory: cms
    - run: pnpm generate:types
      shell: bash
      working-directory: cms
    - run: pnpm copy-types
      shell: bash
      working-directory: frontend
