name: Build
on:
  pull_request:
  push:
    branches:
      - main
    tags:
      - v*
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        required: true
        default: "staging"
        options:
          - staging
          - production

env:
  NODE_VERSION: 20
  PNPM_VERSION: 9
  FLYCTL_VERSION: 0.3.55
  FRONTEND_INTERNAL_PORT: 3000
  CMS_INTERNAL_PORT: 3001
  STORYBOOK_IMAGEKIT_BASE_URL: https://ik.imagekit.io/lapuertahostels/staging
  PREVIEW_IMAGEKIT_BASE_URL: https://ik.imagekit.io/lapuertahostels/preview
  PREVIEW_MEDIA_S3_BUCKET: lapuertahostels-media-preview
  MEDIA_S3_REGION: eu-west-3

jobs:
  frontend-lint:
    name: Frontend / Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
        with:
          working-directory: frontend
      - uses: ./.github/actions/populate-cms-types
      - run: pnpm lint --max-warnings=0
        working-directory: frontend

  frontend-format:
    name: Frontend / Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
        with:
          working-directory: frontend
      - run: pnpm check-format
        working-directory: frontend

  frontend-typecheck:
    name: Frontend / Typecheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
        with:
          working-directory: frontend
      - uses: ./.github/actions/populate-cms-types
      - run: pnpm typecheck
        working-directory: frontend

  frontend-unit-tests:
    name: Frontend / Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
        with:
          working-directory: frontend
      - uses: ./.github/actions/populate-cms-types
      - run: pnpm test
        working-directory: frontend

  frontend-build-push:
    name: Frontend / Build and Push
    runs-on: ubuntu-latest
    permissions:
      packages: write
    outputs:
      image: ${{ steps.image-name.outputs.image }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: ./.github/actions/version
        id: version
      - name: Image name
        id: image-name
        run: |
          echo "image=ghcr.io/${{ github.repository }}-frontend:v${{ steps.version.outputs.version }}" >> "$GITHUB_OUTPUT"
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.frontend
          tags: ${{ steps.image-name.outputs.image }}
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max

  frontend-chromatic:
    name: Frontend / Chromatic
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ./.github/actions/setup
        with:
          working-directory: frontend
      - name: Publish to Chromatic
        uses: chromaui/action@v1
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          exitOnceUploaded: true
          onlyChanged: true
          workingDir: frontend
        env:
          STORYBOOK_IMAGEKIT_BASE_URL: ${{ env.STORYBOOK_IMAGEKIT_BASE_URL }}
          STORYBOOK_USE_IMAGE_CACHE_BUSTER: true
  
  frontend-preview:
    name: Frontend / Preview
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    environment:
      name: preview
      url: ${{ steps.app-name.outputs.app-url }}
    env:
      FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
      FLY_ORG: ${{ vars.FLY_ORG }}
    needs: frontend-build-push
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
        with:
          version: ${{ env.FLYCTL_VERSION }}
      - uses: ./.github/actions/app-name
        id: app-name
        with:
          component: frontend
      - uses: ./.github/actions/app-name
        id: cms-app-name
        with:
          component: cms
      - name: Delete if exists
        run: |
          flyctl apps destroy --yes ${{ steps.app-name.outputs.app-name }} || true
      - name: Create App
        run: |
          echo Creating app ${{ steps.app-name.outputs.app-name }}:
          flyctl apps create --name ${{ steps.app-name.outputs.app-name }} --org $FLY_ORG

          echo Setting secrets:
          flyctl secrets set PAYLOAD_CMS_API_KEY=$PREVIEW_PAYLOAD_CMS_API_KEY \
            SESSION_SECRET=$(openssl rand -hex 32) \
            --app ${{ steps.app-name.outputs.app-name }} --stage
        env:
          PREVIEW_PAYLOAD_CMS_API_KEY: ${{ secrets.PREVIEW_PAYLOAD_CMS_API_KEY }}
        working-directory: frontend
      - name: Deploy
        run: |
          flyctl deploy \
            --app ${{ steps.app-name.outputs.app-name }} \
            --config fly.frontend.preview.toml \
            --ha=false \
            --image ${{ needs.frontend-build-push.outputs.image }} \
            --env IMAGEKIT_BASE_URL=${{ env.PREVIEW_IMAGEKIT_BASE_URL }} \
            --env PAYLOAD_CMS_BASE_URL=${{ steps.cms-app-name.outputs.app-url }} \
            --env CANONICAL_HOSTNAME=${{ steps.app-name.outputs.app-domain }} \

  frontend-deploy:
    name: "Frontend / Deploy"
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request'
    needs:
      - frontend-build-push
      - frontend-chromatic
      - frontend-format
      - frontend-lint
      - frontend-typecheck
      - frontend-unit-tests
      - e2e-tests
      - define-env
    steps:
      - uses: superfly/flyctl-actions/setup-flyctl@master
        with:
          version: ${{ env.FLYCTL_VERSION }}
      - run: |
          flyctl deploy \
            --app ${{ needs.define-env.outputs.fly_app_frontend }} \
            --config fly.frontend.toml \
            --image ${{ needs.frontend-build-push.outputs.image }} \
            --env ANALYTICS_DOMAIN=${{ needs.define-env.outputs.domain_frontend }} \
            --env CANONICAL_HOSTNAME=www.${{ needs.define-env.outputs.domain_frontend }} \
            --env IMAGEKIT_BASE_URL=${{ needs.define-env.outputs.imagekit_base_url }} \
            --env PAYLOAD_CMS_BASE_URL=https://${{ needs.define-env.outputs.domain_cms }} \
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

  cms-format:
    name: CMS / Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
        with:
          working-directory: cms
      - run: pnpm check-format
        working-directory: cms

  cms-build-push:
    name: CMS / Build and Push
    runs-on: ubuntu-latest
    permissions:
      packages: write
    outputs:
      image: ${{ steps.image-name.outputs.image }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: ./.github/actions/version
        id: version
      - name: Image name
        id: image-name
        run: |
          echo "image=ghcr.io/${{ github.repository }}-cms:v${{ steps.version.outputs.version }}" >> "$GITHUB_OUTPUT"
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.cms
          tags: ${{ steps.image-name.outputs.image }}
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max

  cms-preview:
    name: CMS / Preview
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    env:
      FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
      FLY_ORG: ${{ vars.FLY_ORG }}
    needs: cms-build-push
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
        with:
          version: ${{ env.FLYCTL_VERSION }}
      - uses: ./.github/actions/app-name
        id: app-name
        with:
          component: cms
      - uses: ./.github/actions/app-name
        id: frontend-app-name
        with:
          component: frontend
      - name: Delete if exists
        run: |
          flyctl apps destroy --yes ${{ steps.app-name.outputs.app-name }} || true
      - name: Create App
        run: |
          echo Creating app ${{ steps.app-name.outputs.app-name }}:
          flyctl apps create --name ${{ steps.app-name.outputs.app-name }} --org $FLY_ORG

          echo Setting secrets:
          flyctl secrets set DATABASE_URI=$PREVIEW_DATABASE_URI \
            PAYLOAD_SECRET=$PREVIEW_PAYLOAD_SECRET \
            MEDIA_S3_ACCESS_KEY_ID=$PREVIEW_MEDIA_S3_ACCESS_KEY_ID \
            MEDIA_S3_SECRET_ACCESS_KEY=$PREVIEW_MEDIA_S3_SECRET_ACCESS_KEY \
            DEEPL_API_AUTH_KEY=$PREVIEW_DEEPL_API_AUTH_KEY \
            OPENAI_API_KEY="$PREVIEW_OPENAI_API_KEY" \
            --app ${{ steps.app-name.outputs.app-name }} --stage
        env:
          PREVIEW_DATABASE_URI: ${{ secrets.PREVIEW_DATABASE_URI }}
          PREVIEW_PAYLOAD_SECRET: ${{ secrets.PREVIEW_PAYLOAD_SECRET }}
          PREVIEW_MEDIA_S3_ACCESS_KEY_ID: ${{ secrets.PREVIEW_MEDIA_S3_ACCESS_KEY_ID }}
          PREVIEW_MEDIA_S3_SECRET_ACCESS_KEY: ${{ secrets.PREVIEW_MEDIA_S3_SECRET_ACCESS_KEY }}
          PREVIEW_DEEPL_API_AUTH_KEY: ${{ secrets.PREVIEW_DEEPL_API_AUTH_KEY }}
          PREVIEW_OPENAI_API_KEY: ${{ secrets.PREVIEW_OPENAI_API_KEY }}
        working-directory: cms
      - name: Deploy
        run: |
          flyctl deploy \
            --app ${{ steps.app-name.outputs.app-name }} \
            --config fly.cms.toml \
            --ha=false \
            --image ${{ needs.cms-build-push.outputs.image }} \
            --env CACHE_REFRESH_TARGET_TYPE=fly \
            --env CACHE_REFRESH_TARGET_ARG=${{ steps.frontend-app-name.outputs.app-name }},${{ env.FRONTEND_INTERNAL_PORT }} \
            --env MEDIA_S3_BUCKET=${{ env.PREVIEW_MEDIA_S3_BUCKET }} \
            --env MEDIA_S3_REGION=${{ env.MEDIA_S3_REGION }} \
            --env IMAGEKIT_BASE_URL=${{ env.PREVIEW_IMAGEKIT_BASE_URL }} \
            --env LIVE_PREVIEW_URL=${{ steps.frontend-app-name.outputs.app-url }} \

  cms-deploy:
    name: "CMS / Deploy"
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request'
    needs:
      - cms-build-push
      - cms-format
      - e2e-tests
      - define-env
    steps:
      - uses: superfly/flyctl-actions/setup-flyctl@master
        with:
          version: ${{ env.FLYCTL_VERSION }}
      - run: |
          flyctl deploy \
            --app ${{ needs.define-env.outputs.fly_app_cms }} \
            --config fly.cms.toml \
            --image ${{ needs.cms-build-push.outputs.image }} \
            --env CACHE_REFRESH_TARGET_TYPE=fly \
            --env CACHE_REFRESH_TARGET_ARG=${{ needs.define-env.outputs.fly_app_frontend }},${{ env.FRONTEND_INTERNAL_PORT }} \
            --env MEDIA_S3_BUCKET=${{ needs.define-env.outputs.s3_bucket }} \
            --env MEDIA_S3_REGION=${{ env.MEDIA_S3_REGION }} \
            --env IMAGEKIT_BASE_URL=${{ needs.define-env.outputs.imagekit_base_url }} \
            --env LIVE_PREVIEW_URL=https://${{ needs.define-env.outputs.domain_frontend }} \
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

  e2e-tests:
    name: End-to-End Tests
    timeout-minutes: 60
    runs-on: ubuntu-latest
    needs: [frontend-build-push, cms-build-push]
    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: ${{ env.PNPM_VERSION }}
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "pnpm"
          cache-dependency-path: pnpm-lock.yaml
      - name: Install e2e dependencies
        run: pnpm --filter e2e install
      - name: Start services
        run: docker compose up -d && sleep 3
        env:
          FRONTEND_IMAGE: ${{ needs.frontend-build-push.outputs.image }}
          SESSION_SECRET: $(openssl rand -hex 32)
          CMS_IMAGE: ${{ needs.cms-build-push.outputs.image }}
          PAYLOAD_SECRET: $(openssl rand -hex 12)
          PREVIEW_MEDIA_S3_ACCESS_KEY_ID: ${{ secrets.PREVIEW_MEDIA_S3_ACCESS_KEY_ID }}
          PREVIEW_MEDIA_S3_SECRET_ACCESS_KEY: ${{ secrets.PREVIEW_MEDIA_S3_SECRET_ACCESS_KEY }}
          PREVIEW_OPENAI_API_KEY: ${{ secrets.PREVIEW_OPENAI_API_KEY }}
        working-directory: e2e
      - name: Get Playwright version
        id: playwright-version
        run: |
          PLAYWRIGHT_VERSION=$(pnpm list @playwright/test --depth=0 | grep '@playwright/test' | awk '{print $2}')
          echo "playwright_version=${PLAYWRIGHT_VERSION}" >> $GITHUB_OUTPUT
        working-directory: e2e
      - name: Cache Playwright browsers
        uses: actions/cache@v4
        id: playwright-cache
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ steps.playwright-version.outputs.playwright_version }}
      - run: pnpm playwright install --with-deps chromium
        if: steps.playwright-cache.outputs.cache-hit != 'true'
        working-directory: e2e
      - run: pnpm playwright test
        working-directory: e2e
        env:
          FRONTEND_BASE_URL: http://localhost:${{ env.FRONTEND_INTERNAL_PORT }}
          CMS_BASE_URL: http://localhost:${{ env.CMS_INTERNAL_PORT }}
          CMS_API_KEY: apikey
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: e2e/playwright-report/
          retention-days: 30

  clean-preview:
    name: Clean Preview
    uses: ./.github/workflows/clean-preview.yml
    secrets: inherit
    needs: [frontend-preview, cms-preview]
        
  define-env:
    name: Define Environment
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request'
    outputs:
      environment: ${{ steps.define-env.outputs.environment }}
      fly_app_frontend: ${{ steps.define-env.outputs.fly_app_frontend }}
      fly_app_cms: ${{ steps.define-env.outputs.fly_app_cms }}
      domain_frontend: ${{ steps.define-env.outputs.domain_frontend }}
      domain_cms: ${{ steps.define-env.outputs.domain_cms }}
      s3_bucket: ${{ steps.define-env.outputs.s3_bucket }}
      imagekit_base_url: ${{ steps.define-env.outputs.imagekit_base_url }}
    steps:
      - run: |
          environment=${{ inputs.environment || 'staging' }}
          echo "environment=$environment" >> "$GITHUB_OUTPUT"

          case $environment in
            production)
              echo "fly_app_frontend=lapuertahostels-2" >> "$GITHUB_OUTPUT"
              echo "fly_app_cms=lapuertahostels-cms" >> "$GITHUB_OUTPUT"
              echo "domain_frontend=lapuertahostels.co" >> "$GITHUB_OUTPUT"
              echo "domain_cms=admin.lapuertahostels.co" >> "$GITHUB_OUTPUT"
              echo "s3_bucket=lapuertahostels-media" >> "$GITHUB_OUTPUT"
              echo "imagekit_base_url=https://ik.imagekit.io/lapuertahostels" >> "$GITHUB_OUTPUT"
              ;;
            staging)
              echo "fly_app_frontend=lapuertahostels-staging" >> "$GITHUB_OUTPUT"
              echo "fly_app_cms=lapuertahostels-cms-staging" >> "$GITHUB_OUTPUT"
              echo "domain_frontend=staging.lapuertahostels.co" >> "$GITHUB_OUTPUT"
              echo "domain_cms=admin.staging.lapuertahostels.co" >> "$GITHUB_OUTPUT"
              echo "s3_bucket=lapuertahostels-media-staging" >> "$GITHUB_OUTPUT"
              echo "imagekit_base_url=https://ik.imagekit.io/lapuertahostels/staging" >> "$GITHUB_OUTPUT"
              ;;
          esac
        id: define-env

  release:
    name: Release
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    needs:
      - frontend-build-push
      - frontend-chromatic
      - frontend-format
      - frontend-lint
      - frontend-typecheck
      - frontend-unit-tests
      - cms-build-push
      - cms-format
      - e2e-tests
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ./.github/actions/version
      - uses: softprops/action-gh-release@v1
    permissions:
      contents: write
  
  prime-frontend-cache:
    name: "Prime Frontend Cache"
    runs-on: ubuntu-latest
    needs: [define-env, frontend-deploy, cms-deploy]
    environment:
      name: ${{ needs.define-env.outputs.environment }}
      url: https://${{ needs.define-env.outputs.domain_frontend }}/
    steps:
      - run: |
          sleep 30
          curl "https://${{ needs.define-env.outputs.domain_cms }}/api/prime-frontend-cache" \
            -f -s -S \
            -X POST \
            -H "Authorization: users API-Key ${{ secrets.CICD_USER_API_KEY }}"