name: Build
on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      release:
        description: "Create a release"
        required: false
        default: false
        type: boolean

env:
  NODE_VERSION: 22
  FLYCTL_VERSION: 0.3.95
  FRONTEND_INTERNAL_PORT: 3000
  CMS_INTERNAL_PORT: 3001

jobs:
  build:
    name: "Build"
    uses: felixmokross/webplatform/.github/workflows/export.build.yml@main
