name: Build
on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      release:
        description: "Create a release"
        required: false
        default: false
        type: boolean

jobs:
  build:
    name: "Build"
    uses: felixmokross/webplatform/.github/workflows/export.build.yml@main
    permissions:
      contents: write
    secrets: inherit
