name: Check
on:
  pull_request:
  workflow_call:
    secrets:
      CHROMATIC_PROJECT_TOKEN:
        required: true

env:
  NODE_VERSION: 20

jobs:
  frontend-lint:
    name: Frontend / Lint
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/setup.yml
        with:
          working-directory: frontend
      - uses: ./.github/actions/populate-cms-types.yml
      - run: npm run lint -- --max-warnings=0
        working-directory: frontend

  frontend-format:
    name: Frontend / Format
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/setup.yml
        with:
          working-directory: frontend
      - run: npm run check-format
        working-directory: frontend

  frontend-typecheck:
    name: Frontend / Typecheck
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/setup.yml
        with:
          working-directory: frontend
      - uses: ./.github/actions/populate-cms-types.yml
      - run: npm run typecheck
        working-directory: frontend

  frontend-unit-tests:
    name: Frontend / Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/setup.yml
        with:
          working-directory: frontend
      - uses: ./.github/actions/populate-cms-types.yml
      - run: npm run test
        working-directory: frontend

  frontend-build:
    name: Frontend / Build
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/setup.yml
        with:
          working-directory: frontend
      - run: npm run build

  frontend-chromatic:
    name: Chromatic
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/setup.yml
        with:
          working-directory: frontend
          fetch-depth: 0
      - name: Publish to Chromatic
        uses: chromaui/action@v1
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          exitOnceUploaded: true
          onlyChanged: true
          workingDir: frontend
        env:
          STORYBOOK_IMAGEKIT_BASE_URL: https://ik.imagekit.io/lapuertahostels/development

  cms-format:
    name: CMS / Format
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/setup.yml
        with:
          working-directory: cms
      - run: npm run check-format
        working-directory: cms

  cms-build:
    name: CMS / Build
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/setup.yml
        with:
          working-directory: cms
      - run: npm run build
        working-directory: cms
