name: Deploy
on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        required: true
        default: "staging"
        options:
          - staging
          - production

jobs:
  deploy:
    name: "Deploy"
    uses: felixmokross/webplatform/.github/workflows/export.deploy.yml@main
    with:
      environment: ${{ inputs.environment }}
    secrets: inherit
