name: Deploy
on:
  push:
    branches:
      - main
    tags:
      - v*
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        required: true
        default: "staging"
        options:
          - staging
          - production

env:
  NODE_VERSION: 20

jobs:
  version:
    uses: ./.github/workflows/version.yml
  check:
    uses: ./.github/workflows/check.yml
    secrets: inherit
  release:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    needs: check
    steps:
      - uses: softprops/action-gh-release@v1
    permissions:
      contents: write
  define-env:
    runs-on: ubuntu-latest
    outputs:
      environment: ${{ steps.define-env.outputs.environment }}
      fly_app_frontend: ${{ steps.define-env.outputs.fly_app_frontend }}
      fly_app_cms: ${{ steps.define-env.outputs.fly_app_cms }}
      domain_frontend: ${{ steps.define-env.outputs.domain_frontend }}
      domain_cms: ${{ steps.define-env.outputs.domain_cms }}
      imagekit_base_url: ${{ steps.define-env.outputs.imagekit_base_url }}
    steps:
      - id: define-env
        run: |
          environment=${{ inputs.environment || 'staging' }}
          echo "environment=$environment" >> "$GITHUB_OUTPUT"

          case $environment in
            production)
              echo "fly_app_frontend=lapuertahostels-2" >> "$GITHUB_OUTPUT"
              echo "fly_app_cms=lapuertahostels-cms" >> "$GITHUB_OUTPUT"
              echo "domain_frontend=lapuertahostels.co" >> "$GITHUB_OUTPUT"
              echo "domain_cms=lapuertahostels-cms.fly.dev" >> "$GITHUB_OUTPUT"
              echo "imagekit_base_url=https://ik.imagekit.io/lapuertahostels" >> "$GITHUB_OUTPUT"
              ;;
            staging)
              echo "fly_app_frontend=lapuertahostels-staging" >> "$GITHUB_OUTPUT"
              echo "fly_app_cms=lapuertahostels-cms-staging" >> "$GITHUB_OUTPUT"
              echo "domain_frontend=lapuertahostels-staging.fly.dev" >> "$GITHUB_OUTPUT"
              echo "domain_cms=lapuertahostels-cms-staging.fly.dev" >> "$GITHUB_OUTPUT"
              echo "imagekit_base_url=https://ik.imagekit.io/lapuertahostels/staging" >> "$GITHUB_OUTPUT"
              ;;
          esac
        working-directory: .
  deploy-frontend:
    runs-on: ubuntu-latest
    environment:
      name: ${{ needs.define-env.outputs.environment }}
      url: https://${{ needs.define-env.outputs.domain_frontend }}/
    needs: [check, version, define-env]
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
        with:
          version: 0.1.117
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - run: npm version ${{ needs.version.outputs.version }} --git-tag-version false
      - run: |
          flyctl deploy \
            --app ${{ needs.define-env.outputs.fly_app_frontend }} \
            --remote-only \
            --image-label v${{ needs.version.outputs.version }} \
            --env ANALYTICS_DOMAIN=${{ needs.define-env.outputs.domain_frontend }} \
            --env IMAGEKIT_BASE_URL=${{ needs.define-env.outputs.imagekit_base_url }} \
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
  deploy-cms:
    runs-on: ubuntu-latest
    environment:
      name: ${{ needs.define-env.outputs.environment }}
      url: https://${{ needs.define-env.outputs.domain_cms }}/
    needs: [check, version, define-env]
    defaults:
      run:
        working-directory: cms
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
        with:
          version: 0.1.117
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - run: npm version ${{ needs.version.outputs.version }} --git-tag-version false
      - run: |
          flyctl deploy \
            --app ${{ needs.define-env.outputs.fly_app_cms }} \
            --remote-only \
            --image-label v${{ needs.version.outputs.version }} \
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
