name: Deploy
on:
  push:
    branches:
      - main
    tags:
      - v*
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        required: true
        default: "staging"
        options:
          - staging
          - production

env:
  NODE_VERSION: 20

jobs:
  version:
    uses: ./.github/workflows/version.yml
  check:
    uses: ./.github/workflows/check.yml
    secrets: inherit
  release:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    needs: check
    steps:
      - uses: softprops/action-gh-release@v1
    permissions:
      contents: write
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment }}
      url: ${{ inputs.environment == 'production' && 'https://lapuertahostels.co' || 'https://lapuertahostels-staging.fly.dev/' }}
    needs: [check, version]
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
        with:
          version: 0.1.117
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
      - run: npm version ${{ needs.version.outputs.version }} --git-tag-version false
      - run: flyctl deploy --app ${{ inputs.environment == 'production' && 'lapuertahostels-2' || 'lapuertahostels-staging' }} --remote-only --image-label v${{ needs.version.outputs.version }}
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
