name: Deploy
on:
  push:
    branches:
      - main
    tags:
      - v*
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        required: true
        default: "staging"
        options:
          - staging
          - production

env:
  NODE_VERSION: 20

jobs:
  check:
    name: Check
    uses: ./.github/workflows/check.yml
    secrets: inherit

  release:
    name: Release
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    needs: check
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/version
      - uses: softprops/action-gh-release@v1
    permissions:
      contents: write

  deploy-frontend:
    name: "Frontend / Deploy"
    runs-on: ubuntu-latest
    environment:
      name: ${{ steps.define-env.outputs.environment }}
      url: https://${{ steps.define-env.outputs.domain_frontend }}/
    needs: check
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
        with:
          version: 0.1.117
      - uses: ./.github/actions/version
        id: version
      - uses: ./.github/actions/define-env
        id: define-env  
        with:
          environment: ${{ inputs.environment }}
      - run: |
          flyctl deploy \
            --app ${{ steps.define-env.outputs.fly_app_frontend }} \
            --remote-only \
            --image-label v${{ steps.version.outputs.version }} \
            --env ANALYTICS_DOMAIN=${{ steps.define-env.outputs.domain_frontend }} \
            --env IMAGEKIT_BASE_URL=${{ steps.define-env.outputs.imagekit_base_url }} \
            --env PAYLOAD_CMS_BASE_URL=https://${{ steps.define-env.outputs.domain_cms }}/api \
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

  deploy-cms:
    name: "CMS / Deploy"
    runs-on: ubuntu-latest
    needs: check
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
        with:
          version: 0.1.117
      - uses: ./.github/actions/version
        id: version
      - uses: ./.github/actions/define-env
        id: define-env  
        with:
          environment: ${{ inputs.environment }}
      - run: |
          flyctl deploy \
            --app ${{ steps.define-env.outputs.fly_app_cms }} \
            --remote-only \
            --image-label v${{ steps.version.outputs.version }} \
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
