name: Preview
on:
  pull_request:

env:
  NODE_VERSION: 20
  IMAGEKIT_BASE_URL: https://ik.imagekit.io/lapuertahostels

jobs:
  frontend-preview:
    name: Frontend / Preview
    runs-on: ubuntu-latest
    environment:
      name: preview
      url: ${{ steps.app-name.outputs.app-url }}
    env:
      FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
      FLY_ORG: personal
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: superfly/flyctl-actions/setup-flyctl@master
        with:
          version: 0.1.117
      - uses: ./.github/actions/app-name
        id: app-name
        with:
          component: frontend
      - uses: ./.github/actions/app-name
        id: cms-app-name
        with:
          component: cms
      - name: Delete if exists
        run: |
          flyctl apps destroy --yes ${{ steps.app-name.outputs.app-name }} || true
      - name: Create App
        run: |
          echo Creating app ${{ steps.app-name.outputs.app-name }}:
          flyctl apps create --name ${{ steps.app-name.outputs.app-name }} --org $FLY_ORG
      - uses: ./.github/actions/version
        id: version
      - name: Deploy
        run: |
          flyctl deploy \
            --app ${{ steps.app-name.outputs.app-name }} \
            --config ./fly.preview.toml \
            --image-label v${{ steps.version.outputs.version }} \
            --env IMAGEKIT_BASE_URL=${{ env.IMAGEKIT_BASE_URL }} \
            --env PAYLOAD_CMS_BASE_URL=${{ steps.cms-app-name.outputs.app-url }} \
        working-directory: frontend

  cms-preview:
    name: CMS / Preview
    runs-on: ubuntu-latest
    env:
      FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
      FLY_ORG: personal
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: superfly/flyctl-actions/setup-flyctl@master
        with:
          version: 0.1.117
      - uses: ./.github/actions/app-name
        id: app-name
        with:
          component: cms
      - uses: ./.github/actions/app-name
        id: frontend-app-name
        with:
          component: frontend
      - name: Delete if exists
        run: |
          flyctl apps destroy --yes ${{ steps.app-name.outputs.app-name }} || true
      - name: Create App
        run: |
          echo Creating app ${{ steps.app-name.outputs.app-name }}:
          flyctl apps create --name ${{ steps.app-name.outputs.app-name }} --org $FLY_ORG

          echo Setting secrets:
          flyctl secrets set DATABASE_URI=$PREVIEW_DATABASE_URI \
            PAYLOAD_SECRET=$(openssl rand -hex 12) \
            --app ${{ steps.app-name.outputs.app-name }} --stage
        env:
          PREVIEW_DATABASE_URI: ${{ secrets.PREVIEW_DATABASE_URI }}
      - uses: ./.github/actions/version
        id: version
      - name: Deploy
        run: |
          flyctl deploy \
            --app ${{ steps.app-name.outputs.app-name }} \
            --image-label v${{ steps.version.outputs.version }} \
            --env LIVE_PREVIEW_URL=${{ steps.frontend-app-name.outputs.app-url }} \
        working-directory: cms

  clean-preview:
    name: Clean Preview
    uses: ./.github/workflows/clean-preview.yml
    secrets: inherit
    needs: [frontend-preview, cms-preview]
