name: Preview Clean
on:
  schedule:
    - cron: "0 2 * * *"
  workflow_dispatch:
  workflow_call:
    secrets:
      FLY_API_TOKEN:
        required: true

jobs:
  clean:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
        with:
          version: 0.1.117
      - run: |
          flyctl apps list --json --org $FLY_ORG \
            | jq '[map(
              { ID, LastReleasedAt: .CurrentRelease.CreatedAt }
              | select(.ID | test("^lapuertahostels-preview-"))
              | {
                  ID,
                  LastReleasedDaysAgo: (
                    if .LastReleasedAt == null
                      then null
                      else ((now - (.LastReleasedAt | fromdate)) / 60 / 60 / 24)
                    end
                  )
                }
            )]
            | map((. | map(select(.LastReleasedDaysAgo == null or .LastReleasedDaysAgo > 4))), (.
                | sort_by(.LastReleasedDaysAgo)
                | .[3:])
            )
            | flatten
            | unique_by(.ID)
            | map(.ID)
            | .[]' \
              | xargs -I {} flyctl apps destroy --yes {}
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
          FLY_ORG: personal
