name: Preview Clean
on:
  workflow_dispatch:
  workflow_call:
    secrets:
      FLY_API_TOKEN:
        required: true

jobs:
  clean:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
        with:
          version: 0.1.117
      - run: |
          flyctl apps list --json --org $FLY_ORG \
            | jq '[
                .[]
                  | { ID:.ID, LastReleasedAt: .CurrentRelease.CreatedAt }
                  | select(.ID | (test("^lapuertahostels-preview-") and (test("-db$") | not)))
              ]
                | sort_by(.LastReleasedAt)
                | reverse
                | .[3:]
                | map(.ID, .ID + "-db")
                | .[]' \
              | xargs -I {} flyctl apps destroy --yes {}
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
          FLY_ORG: personal
